#!/bin/bash
set -euo pipefail

# ./test/create-proxy-backup


PATH=$PATH:$PWD/../node_modules/serverless/bin
[ ! `which serverless` ] && echo "No serverless binary in PATH" && exit 1

# AWS credentials are being passed as a faile
#   ./.aws/credentials to serverless local

# export SLS_DEBUG=*

serverless invoke local \
  -f check-bash-layer

